### ISSUE TITLE
load() missing 1 required positional argument: 'Loader'

### ISSUE THREAD

**Issue by gborbeke** [jbudis/snakelines#60]
Hi!

I installed SnakeLines frome Github, but when I tried to run an example, I'v got the following errors:

snakemake \
	--snakefile /usr/local/snakelines/snakelines.snake \
	--configfile config_variant_calling.yaml \
	--use-conda
 
Error: you need to specify the maximum number of CPU cores to be used at the same time with --cores.

So I added the --cores parameter, but the I've run into this:

snakemake \
	--snakefile /usr/local/snakelines/snakelines.snake \
	--configfile config_variant_calling.yaml \
	--use-conda --cores 8

Importing snakefile: /usr/local/snakelines/rules/paired_end/reads/preprocess/trimmed/trimmomatic.snake
Importing snakefile: /usr/local/snakelines/rules/paired_end/reads/preprocess/decontaminated/bowtie2.snake
Importing snakefile: /usr/local/snakelines/rules/paired_end/reads/preprocess/deduplicated/fastuniq.snake
Importing snakefile: /usr/local/snakelines/rules/paired_end/reads/report/quality_report/fastqc.snake
Importing snakefile: /usr/local/snakelines/rules/paired_end/mapping/mapper/bowtie2.snake
Multiple include of /usr/local/snakelines/rules/shared/mapping/mapper/indices/bowtie2_index.snake ignored
Importing snakefile: /usr/local/snakelines/rules/shared/mapping/index/samtools.snake
Importing snakefile: /usr/local/snakelines/rules/shared/mapping/postprocess/sorted/samtools.snake
Importing snakefile: /usr/local/snakelines/rules/shared/mapping/postprocess/read_group/custom.snake
Importing snakefile: /usr/local/snakelines/rules/shared/mapping/postprocess/deduplicated/picard.snake
Importing snakefile: /usr/local/snakelines/rules/shared/mapping/postprocess/filtered/bamtools.snake
Importing snakefile: /usr/local/snakelines/rules/paired_end/mapping/report/quality_report/qualimap.snake
Importing snakefile: /usr/local/snakelines/rules/shared/variant/caller/vardict.snake
TypeError in line 45 of /usr/local/snakelines/snakelines.snake:
load() missing 1 required positional argument: 'Loader'
  File "/usr/local/snakelines/snakelines.snake", line 45, in <module>
  File "/usr/local/snakelines/src/config/dependency_load.py", line 69, in check_dependency
  File "/usr/local/snakelines/src/config/dependency_load.py", line 15, in load_yaml

**Comment by wernerkrampl** [comment]
Hi, this bug was connected to the oyaml package. It was fixed in version 1.1.0.
